"""removed tempImage column

Revision ID: cbdb958df1c0
Revises: e4c895d13a21
Create Date: 2025-11-25 07:38:48.036529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbdb958df1c0'
down_revision: Union[str, Sequence[str], None] = 'e4c895d13a21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'tempimage')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('tempimage', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
