"""added temporary image storage3

Revision ID: e4c895d13a21
Revises: f747c80585a5
Create Date: 2025-11-25 06:53:05.722370

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e4c895d13a21"
down_revision: Union[str, Sequence[str], None] = "f747c80585a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("tempimage", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("posts", "tempimage")
    # ### end Alembic commands ###
